version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      intellij-platform:
        patterns:
          - "org.jetbrains.intellij*"
          - "org.jetbrains.kotlin*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
